version: '3'
services:
  login-app:
    container_name: bit-todo
    image: latest123/bit-todo
    restart: always
    build: .
    ports:
      - '7500:7500'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
